/*
   FALCON - The Falcon Programming Language.
   FILE: linkerror.h

   Error generated by the linker.
   -------------------------------------------------------------------
   Author: Giancarlo Niccolai
   Begin: Sun, 31 Jul 2011 15:30:08 +0200

   -------------------------------------------------------------------
   (C) Copyright 2011: the FALCON developers (see list in AUTHORS file)

   See LICENSE file for licensing details.
*/


#ifndef FALCON_LINKERROR_H
#define FALCON_LINKERROR_H

#include <falcon/error.h>

namespace Falcon {

/** Error generated by the linker during the link process.
 */
class FALCON_DYN_CLASS LinkError: public Error
{
public:
   LinkError( );
   LinkError( const ErrorParam &params );

protected:
   virtual ~LinkError();
};

}

#endif	/* FALCON_linkerror_H */

/* end of linkerror.h */
