.\" Process this file with
.\" groff -man -Tascii falcon-conf.1
.\"
.TH falcon\-conf 1 "July 2007" "Falcon toolset" "Falcon User Manuals"
.SH NAME

falcon\-conf \- Falcon makefile settings helper

.SH SYNOPSIS

.B falcon\-conf [options]

.SH DESCRIPTION

The
.B falcon\-conf
script can be used to determine automatically Falcon development file
installation path and settings for include and library options in
compilers.

.B falcon\-conf
is written mainly to work with GNU gcc and make, but
it provides also options to determine solely the paths or the files
to be included or linked, stripped of GNU options.

.SH OPTIONS

Please, refer to the inline option list, which is available calling
.B falcon\-conf
without any parameter.

.SH BUGS

None known

.SH AUTHOR

Giancarlo Niccolai <gc@falconpl.org>

.SH "SEE ALSO"

.BR falcon (1)

.SH LICENSE
This document is released under the "GNU Free Documentation License, version 1.2".
On Debian systems, the complete text of the Free Documentation License, version 1.2,
can be found in /usr/share/common\-licenses/.

