/*
   FALCON - The Falcon Programming Language.
   FILE: errorclasses.h

   All the Class handling errors generated by the engine.
   -------------------------------------------------------------------
   Author: Giancarlo Niccolai
   Begin: Sun, 31 Jul 2011 15:30:08 +0200

   -------------------------------------------------------------------
   (C) Copyright 2011: the FALCON developers (see list in AUTHORS file)

   See LICENSE file for licensing details.
*/

#undef SRC
#define SRC "engine/errorclasses.cpp"

#include <falcon/vmcontext.h>

//--- error headers ---
#include <falcon/classes/classerror.h>

#include <falcon/errors/accesserror.h>
#include <falcon/errors/accesstypeerror.h>
#include <falcon/errors/codeerror.h>
#include <falcon/errors/genericerror.h>
#include <falcon/errors/interruptederror.h>
#include <falcon/errors/ioerror.h>
#include <falcon/errors/operanderror.h>
#include <falcon/errors/unsupportederror.h>
#include <falcon/errors/syntaxerror.h>
#include <falcon/errors/encodingerror.h>
#include <falcon/errors/linkerror.h>
#include <falcon/errors/paramerror.h>
#include <falcon/errors/matherror.h>
#include <falcon/errors/unserializableerror.h>
#include <falcon/errorclasses.h>

// Initialization

#define FALCON_DEFINE_ERROR_CLASSES
#include <falcon/errorclasses.h>

/* end of errorclasses.cpp */
