set(FALCON_VERSION_MAJOR 0)
set(FALCON_VERSION_MINOR 9)
set(FALCON_VERSION_REVISION 6)
set(FALCON_VERSION_PATCH 3)

set(FALCON_VERSION_NAME "Chimera")

set(FALCON_SONAME_VERSION 1)
set(FALCON_SONAME_REVISION 21)
set(FALCON_SONAME_AGE 1)

