set(FALCON_VERSION_MAJOR 0)
set(FALCON_VERSION_MINOR 9)
set(FALCON_VERSION_REVISION 9)
set(FALCON_VERSION_PATCH 0)

set(FALCON_VERSION_NAME "Peregrine")

set(FALCON_SONAME_VERSION 2)
set(FALCON_SONAME_REVISION 0)
set(FALCON_SONAME_AGE 0)

