set(FALCON_VERSION_MAJOR 1)
set(FALCON_VERSION_MINOR 0)
set(FALCON_VERSION_REVISION 0)
set(FALCON_VERSION_PATCH 0)

set(FALCON_VERSION_NAME "Peregrine")
set(FALCON_VERSION_SPEC "alpha")
set(FALCON_VERSION_BUILD_ID 0)

set(FALCON_SONAME_VERSION 2)
set(FALCON_SONAME_REVISION 0)
set(FALCON_SONAME_AGE 0)

