/*
   FALCON - The Falcon Programming Language.
   FILE: errors.h

   Error for WOPI exceptions.

   -------------------------------------------------------------------
   Author: Giancarlo Niccolai
   Begin: Sun, 28 Mar 2010 17:12:01 +0200

   -------------------------------------------------------------------
   (C) Copyright 2010: the FALCON developers (see list in AUTHORS file)

   See LICENSE file for licensing details.
*/

#ifndef WOPI_ERROR_H
#define WOPI_ERROR_H

#include <falcon/error.h>
#include <falcon/error_base.h>

#ifndef FALCON_ERROR_WOPI_BASE
   #define FALCON_ERROR_WOPI_BASE            2400
#endif

#define FALCON_ERROR_WOPI_SESS_ALREADY       (FALCON_ERROR_WOPI_BASE + 0 )
#define FALCON_ERROR_WOPI_SESS_CLOSED        (FALCON_ERROR_WOPI_BASE + 1 )
#define FALCON_ERROR_WOPI_SESS_AFTER_OUT     (FALCON_ERROR_WOPI_BASE + 2 )
#define FALCON_ERROR_WOPI_APPDATA_SER        (FALCON_ERROR_WOPI_BASE + 3 )
#define FALCON_ERROR_WOPI_APPDATA_DESER      (FALCON_ERROR_WOPI_BASE + 4 )
#define FALCON_ERROR_WOPI_PERSIST_NOT_FOUND  (FALCON_ERROR_WOPI_BASE + 5 )
#define FALCON_ERROR_WOPI_FIELD_NOT_FOUND    (FALCON_ERROR_WOPI_BASE + 6 )
#define FALCON_ERROR_WOPI_INVALID_CONFIG     (FALCON_ERROR_WOPI_BASE + 7 )
#define FALCON_ERROR_WOPI_UPLOAD_TOO_BIG     (FALCON_ERROR_WOPI_BASE + 8 )
#define FALCON_ERROR_WOPI_IO                 (FALCON_ERROR_WOPI_BASE + 9 )
#define FALCON_ERROR_WOPI_REQUEST_PARSE      (FALCON_ERROR_WOPI_BASE + 10 )

namespace Falcon {

/*#
 @class PersistError
 @brief Error raised when problems saving or restoring persistent data are detected.
 */
   FALCON_DECLARE_ERROR_INSTANCE( PersistError );
   FALCON_DECLARE_ERROR_CLASS_EX( PersistError, \
            addConstant("NotFound", FALCON_ERROR_WOPI_PERSIST_NOT_FOUND );\
            );

/*#
   @class WopiError
   @brief Error generated by WOPI in case of failures.
   @optparam code A numeric error code.
   @optparam description A textual description of the error code.
   @optparam extra A descriptive message explaining the error conditions.
   @from Error code, description, extra

   Possible error codes are:
   - WopiError.SessionAlready -Session already started
   - WopiError.SessionAlready - Session already closed
   - WopiError.SessionOutput - Session started after output
   - WopiError.AppDataStore - Cannot store/save application specific data.
   - WopiError.AppDataRestore - Cannot restore application-specific data.
   - WopiError.PeristNotFound - Persistent data not found.
   - WopiError.FieldNotFound - Required field was not presented in the remote request.
   - WopiError.InvalidConfigKey - Invalid configuration key.
   - WopiError.UploadTooBig - Uploaded file is too big.
   - WopiError.IO - Generic input/output error during an essential operation.
   - WopiError.RequestParse - Error while parsing incoming web request.

*/
FALCON_DECLARE_ERROR_INSTANCE_WITH_DESC( WopiError,
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_SESS_ALREADY, "Session already started" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_SESS_CLOSED, "Session already closed" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_SESS_AFTER_OUT, "Session started after output" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_APPDATA_SER, "Cannot store/save application specific data" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_APPDATA_DESER, "Cannot restore application-specific data" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_PERSIST_NOT_FOUND, "Required field was not presented in the remote request" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_INVALID_CONFIG, "Invalid configuration key or value" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_UPLOAD_TOO_BIG, "Upload too big" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_IO, "Generic input/output error" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_WOPI_REQUEST_PARSE, "Error while parsing incoming web request" )
);
FALCON_DECLARE_ERROR_CLASS_EX( WopiError, \
         addConstant("SessionAlready", FALCON_ERROR_WOPI_SESS_ALREADY );\
         addConstant("SessionClosed", FALCON_ERROR_WOPI_SESS_CLOSED );\
         addConstant("SessionOutput", FALCON_ERROR_WOPI_SESS_AFTER_OUT);\
         addConstant("AppDataStore", FALCON_ERROR_WOPI_APPDATA_SER);\
         addConstant("AppDataRestore", FALCON_ERROR_WOPI_APPDATA_DESER);\
         addConstant("PeristNotFound", FALCON_ERROR_WOPI_PERSIST_NOT_FOUND);\
         addConstant("FieldNotFound", FALCON_ERROR_WOPI_FIELD_NOT_FOUND);\
         addConstant("InvalidConfigKey", FALCON_ERROR_WOPI_INVALID_CONFIG);\
         addConstant("UploadTooBig", FALCON_ERROR_WOPI_UPLOAD_TOO_BIG); \
         addConstant("IO", FALCON_ERROR_WOPI_IO ); \
         addConstant("RequestParse", FALCON_ERROR_WOPI_REQUEST_PARSE );
         )
}

#endif

/* end of errors.h */
