/*
   FALCON - The Falcon Programming Language.
   FILE: errors.h

   Error for WOPI exceptions.

   -------------------------------------------------------------------
   Author: Giancarlo Niccolai
   Begin: Sun, 28 Mar 2010 17:12:01 +0200

   -------------------------------------------------------------------
   (C) Copyright 2010: the FALCON developers (see list in AUTHORS file)

   See LICENSE file for licensing details.
*/

#ifndef WOPI_ERROR_H
#define WOPI_ERROR_H

#include <falcon/error.h>
#include <falcon/error_base.h>

#ifndef FALCON_ERROR_WOPI_BASE
   #define FALCON_ERROR_WOPI_BASE            2400
#endif

#define FALCON_ERROR_WOPI_SESS_IO            (FALCON_ERROR_WOPI_BASE + 0 )
#define FALCON_ERROR_WOPI_SESS_EXPIRED       (FALCON_ERROR_WOPI_BASE + 1 )
#define FALCON_ERROR_WOPI_APPDATA_SER        (FALCON_ERROR_WOPI_BASE + 2 )
#define FALCON_ERROR_WOPI_APPDATA_DESER      (FALCON_ERROR_WOPI_BASE + 3 )
#define FALCON_ERROR_WOPI_SESS_INVALID_ID    (FALCON_ERROR_WOPI_BASE + 4 )
#define FALCON_ERROR_WOPI_PERSIST_NOT_FOUND  (FALCON_ERROR_WOPI_BASE + 5 )
#define FALCON_ERROR_WOPI_FIELD_NOT_FOUND    (FALCON_ERROR_WOPI_BASE + 6 )

namespace Falcon {

/*#
 @class PersistError
 @brief Error raised when problems saving or restoring persistent data are detected.
 */
   FALCON_DECLARE_ERROR_INSTANCE( PersistError );
   FALCON_DECLARE_ERROR_CLASS_EX( PersistError, \
            addConstant("NotFound", FALCON_ERROR_WOPI_PERSIST_NOT_FOUND );\
            );

/*#
   @class WopiError
   @brief Error generated by WOPI in case of failures.
   @optparam code A numeric error code.
   @optparam description A textual description of the error code.
   @optparam extra A descriptive message explaining the error conditions.
   @from Error code, description, extra

   Possible error codes are:
   - WopiError.SessionIO - I/O error in storing or restoring a session.
   - WopiError.SessionExipred - The session is expired.
   - WopiError.AppDataStore - Cannot store/save application specific data.
   - WopiError.AppDataRestore - Cannot restore application-specific data.
   - WopiError.SessionInvalid - The session data is invalid.

*/
FALCON_DECLARE_ERROR_INSTANCE( WopiError );
FALCON_DECLARE_ERROR_CLASS_EX( WopiError, \
         addConstant("SessionIO", FALCON_ERROR_WOPI_SESS_IO );\
         addConstant("SessionExipred", FALCON_ERROR_WOPI_SESS_EXPIRED);\
         addConstant("AppDataStore", FALCON_ERROR_WOPI_APPDATA_SER);\
         addConstant("AppDataRestore", FALCON_ERROR_WOPI_APPDATA_DESER);\
         addConstant("SessionInvalid", FALCON_ERROR_WOPI_SESS_INVALID_ID);\
         addConstant("PeristNotFound", FALCON_ERROR_WOPI_PERSIST_NOT_FOUND);\
         addConstant("FieldNotFound", FALCON_ERROR_WOPI_FIELD_NOT_FOUND);\
         )
}

#endif

/* end of errors.h */
