/*
   FALCON - The Falcon Programming Language.
   FILE: errors.h

   Errors for containers.
   -------------------------------------------------------------------
   Author: Giancarlo Niccolai
   Begin: Sat, 24 Apr 2010 12:12:10 +0200

   -------------------------------------------------------------------
   (C) Copyright 2013: the FALCON developers (see list in AUTHORS file)

   See LICENSE file for licensing details.
*/



#ifndef _FALCON_FEATHERS_CONTAINERS_ERRORS_H_
#define _FALCON_FEATHERS_CONTAINERS_ERRORS_H_

#include <falcon/setup.h>
#include <falcon/error.h>
#include <falcon/error_base.h>

#ifndef FALCON_CONTAINERS_ERROR_BASE
#define FALCON_CONTAINERS_ERROR_BASE           1260
#endif

#define FALCON_ERROR_CONTAINERS_OUTSYNC   (FALCON_SHMEM_ERROR_BASE + 0 )
#define FALCON_ERROR_CONTAINERS_INVITER   (FALCON_SHMEM_ERROR_BASE + 1 )
#define FALCON_ERROR_CONTAINERS_EMPTY     (FALCON_SHMEM_ERROR_BASE + 2 )
#define FALCON_ERROR_CONTAINERS_EOF       (FALCON_SHMEM_ERROR_BASE + 3 )
#define FALCON_ERROR_CONTAINERS_NOINS     (FALCON_SHMEM_ERROR_BASE + 4 )

namespace Falcon {
/*#
   @class ContainerError
   @brief Error generated by the container module in case of failures.
   @optparam code A numeric error code.
   @optparam description A textual description of the error code.
   @optparam extra A descriptive message explaining the error conditions.
   @from Error code, description, extra

   Possible error codes are:
   - ContainerError.OutOfSync - The container changed while performing an iterator operation.
   - ContainerError.InvalidIterator - The iterator given in an operation isn't created on this container.
   - ContainerError.Empty - Removing items from an empty container.
   - ContainerError.Eof - Iterators moved past the last element.
   - ContainerError.NotInsertable - The container doesn't support positional insertion.
*/
FALCON_DECLARE_ERROR_INSTANCE_WITH_DESC( ContainerError,
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_CONTAINERS_OUTSYNC, "The container changed while performing an iterator operation" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_CONTAINERS_INVITER, "The iterator given in an operation isn't created on this container" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_CONTAINERS_EMPTY, "Removing items from an empty container" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_CONTAINERS_EOF, "Iterators moved past the last element" )
         FALCON_ERROR_CLASS_DESC( FALCON_ERROR_CONTAINERS_NOINS, "The container doesn't support positional insertion" )
);
FALCON_DECLARE_ERROR_CLASS_EX( ContainerError, \
         addConstant("OutOfSync", FALCON_ERROR_CONTAINERS_OUTSYNC );\
         addConstant("InvalidIterator", FALCON_ERROR_CONTAINERS_INVITER );\
         addConstant("Empty", FALCON_ERROR_CONTAINERS_EMPTY );\
         addConstant("NotInsertable", FALCON_ERROR_CONTAINERS_EOF );\
         )
}

#endif /* _FALCON_FEATHERS_CONTAINERS_ERRORS_H_ */

/* end of errors.h */
