/*
   FALCON - The Falcon Programming Language.
   FILE: errorclasses.h

   All the Class handling errors generated by the engine.
   -------------------------------------------------------------------
   Author: Giancarlo Niccolai
   Begin: Sun, 31 Jul 2011 15:30:08 +0200

   -------------------------------------------------------------------
   (C) Copyright 2011: the FALCON developers (see list in AUTHORS file)

   See LICENSE file for licensing details.
*/

#ifndef _FALCON_ERRORCLASSES_H_
#define _FALCON_ERRORCLASSES_H_

#include <falcon/classes/classerror.h>

namespace Falcon {
   #include <falcon/errors/errorclasses_list.h>
}

#endif	/* _FALCON_ERRORCLASSES_H_ */

/* end of errorclasses.h */
