/*
   FALCON - The Falcon Programming Language.
   FILE: parser/terminal.h

   Token representing a terminal grammar symbol.
   -------------------------------------------------------------------
   Author: Giancarlo Niccolai
   Begin: Fri, 08 Apr 2011 16:44:42 +0200

   -------------------------------------------------------------------
   (C) Copyright 2011: the FALCON developers (see list in AUTHORS file)

   See LICENSE file for licensing details.
*/

#ifndef _FALCON_PARSER_TERMINAL_H_
#define	_FALCON_PARSER_TERMINAL_H_

#include <falcon/setup.h>
#include <falcon/parser/token.h>

namespace Falcon {
namespace Parser {

/** Terminal symbols.
 Terminal symbols represent an instance of definition that cannot be furtherly
 broken up. It is directly generated by the lexer having a defined value.
 
 For example, see the definition of TString terminal symbol.

 */
class FALCON_DYN_CLASS Terminal: public Token
{
public:
   inline virtual ~Terminal() {}

protected:
   inline Terminal(const String& name):
      Token( name )
      {}
};

}
}

#endif	/* _FALCON_PARSER_TERMINAL_H_ */

/* end of parser/terminal.h */
